apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ .Values.appName | quote }}
  labels:
    app: {{ .Values.appName | quote }}
    version: {{ .Values.version | quote }}
spec:
  predictor:
    runtime: kserve-tensorflow-serving  #kserve tensorflow serving이 업데이트 안되는 문제 발생
    model:
      modelFormat:
        name: {{ .Values.modelFormat }}
      storageUri: {{ .Values.storageUri }}